# Generated by Django 4.2.1 on 2023-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("COMMON", "COMMON"), ("NEMO", "NEMO")], max_length=15
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
