# Generated by Django 4.2.1 on 2023-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMMON", "COMMON"),
                            ("NEMO", "NEMO"),
                            ("ADMIN", "ADMIN"),
                        ],
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(default="")),
                ("is_student", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
