# Generated by Django 4.2.1 on 2023-05-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("post_num", models.CharField(max_length=15)),
                ("approved_at", models.DateTimeField()),
                ("content", models.TextField(default="")),
                ("password", models.CharField(max_length=4)),
                ("is_student", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False, null=True)),
                ("filtered_content", models.TextField(default="")),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
