# Generated by Django 4.2.1 on 2023-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_post_is_deleted_post_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
