# Generated by Django 4.2.1 on 2023-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_comment_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
