# Generated by Django 4.2.1 on 2023-05-19 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_post_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerComment",
            fields=[],
            options={
                "verbose_name": "댓글 (관리자용)",
                "verbose_name_plural": "댓글들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("post.comment",),
        ),
        migrations.CreateModel(
            name="MaintainerPost",
            fields=[],
            options={
                "verbose_name": "게시글 (관리자용)",
                "verbose_name_plural": "게시글들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("post.post",),
        ),
    ]
