# Generated by Django 4.2.1 on 2023-05-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="filtered_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="report",
            name="is_approved",
            field=models.BooleanField(null=True),
        ),
    ]
