# Generated by Django 4.2.1 on 2023-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreport",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="commentreport",
            name="filtered_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="commonreport",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="commonreport",
            name="filtered_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="nemoreport",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="nemoreport",
            name="filtered_content",
            field=models.TextField(default=""),
        ),
    ]
