# Generated by Django 4.2.1 on 2023-05-19 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_alter_report_filtered_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonReport",
            fields=[],
            options={
                "verbose_name": "일반 제보 (관리자용)",
                "verbose_name_plural": "일반 제보들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("report.report",),
        ),
        migrations.CreateModel(
            name="NemoReport",
            fields=[],
            options={
                "verbose_name": "니모 제보 (관리자용)",
                "verbose_name_plural": "니모 제보들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("report.report",),
        ),
    ]
