# Generated by Django 4.2.1 on 2023-05-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_deleted_at"),
        ("report", "0003_remove_commentreport_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreport",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentreport",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentreport",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
        migrations.AlterField(
            model_name="commonreport",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commonreport",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
        migrations.AlterField(
            model_name="nemoreport",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nemoreport",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
