# Generated by Django 4.2.1 on 2023-05-19 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0003_commonreport_nemoreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommonReport",
        ),
        migrations.DeleteModel(
            name="NemoReport",
        ),
        migrations.CreateModel(
            name="MaintainerCommonReport",
            fields=[],
            options={
                "verbose_name": "일반 제보 (관리자용)",
                "verbose_name_plural": "일반 제보들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("report.report",),
        ),
        migrations.CreateModel(
            name="MaintainerNemoReport",
            fields=[],
            options={
                "verbose_name": "니모 제보 (관리자용)",
                "verbose_name_plural": "니모 제보들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("report.report",),
        ),
        migrations.CreateModel(
            name="MaintainerQuestion",
            fields=[],
            options={
                "verbose_name": "재학생 인증 질문 (관리자용)",
                "verbose_name_plural": "재학생 인증 질문들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("report.question",),
        ),
    ]
