# Generated by Django 4.2.1 on 2023-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0002_alter_notice_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="notice",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
