# Generated by Django 4.2.1 on 2023-05-19 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerSuggestion",
            fields=[],
            options={
                "verbose_name": "건의사항 (관리자용)",
                "verbose_name_plural": "건의사항들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suggestion.suggestion",),
        ),
    ]
